S03 exhibition index
lbf-2974/0322_P3_Php_Lyon_Irep pull request #3
Opened 2023-06-26 08:32 UTC by lbf-2974

Exhibition updates : controller, edit, delete.
And presentations associated, no more list of all presentations.

2023-06-26 12:14 UTC, aldaitzwild requested changes

2023-06-26 12:14 UTC, aldaitzwild commented on src/Controller/ExhibitionController.php
> +    #[Route('/{exhibitionName}', methods: ['GET'], name: 'exhibition_show_presentation')]
Why do you use as a route identifier an attribute who is not unique ?

2023-06-26 14:10 UTC, lbf-2974 commented
Changes done, attribute for the route is now an id.

2023-06-27 09:56 UTC, aldaitzwild approved these changes

2023-06-27 09:56 UTC, merged